window.POA_EVIDENCE = [
  {
    id: "openai-credit-checks-2026-09",
    date: "2026-09-16",
    title: "OpenAI says AI reduced the people needed for routine finance work",
    level: "observed",
    levelLabel: "Observed development",
    topics: ["first-rung", "cognitive-work", "corporate-adoption", "hiring-wages"],
    topicLabels: ["First Rung", "Cognitive Work", "Corporate Adoption", "Hiring & Wages"],
    summary: "OpenAI Chief Financial Officer Sarah Friar said the company uses AI for routine finance work such as procurement credit checks. She said the work had previously been done by junior analysts, that AI limits the number of people needed for such tasks, and that the cost per check fell from about $200 to about $0.17.",
    why: "This is unusually direct evidence from inside a major AI company that a cognitive task previously assigned to junior staff can be automated at a dramatically lower unit cost. It is directly relevant to the Missing First Rung argument.",
    limits: "It does not tell us how many jobs were eliminated, whether affected workers were reassigned, or whether the same economics will apply across every company or finance task.",
    source: "Yahoo Finance / Business Insider report of CNBC interview",
    sourceType: "Reported executive statement",
    url: "https://finance.yahoo.com/technology/ai/articles/openais-cfo-says-ai-replacing-040101276.html"
  },
  {
    id: "stanford-young-workers-2026-08",
    date: "2026-08-12",
    title: "Young workers in AI-exposed occupations show a widening employment gap",
    level: "signal",
    levelLabel: "Emerging signal",
    topics: ["first-rung", "hiring-wages", "cognitive-work"],
    topicLabels: ["First Rung", "Hiring & Wages", "Cognitive Work"],
    summary: "Stanford Digital Economy Lab researchers, using ADP payroll data through June 2026, report no broad economy-wide AI displacement. But among workers ages 22–25, employment in AI-exposed occupations stood 19% below where it would have been had it kept pace with less-exposed peers; experienced workers did not show the same gap.",
    why: "The age pattern is consistent with the possibility that AI pressure may first appear through hiring pipelines and junior roles rather than mass layoffs across all workers.",
    limits: "The study is descriptive evidence, not proof that AI caused the entire gap. Broader labor-market conditions can also affect hiring, and the authors explicitly do not find economy-wide displacement.",
    source: "Stanford Digital Economy Lab",
    sourceType: "Academic working paper",
    url: "https://digitaleconomy.stanford.edu/publication/canaries-in-the-coal-mine-six-facts-about-the-recent-employment-effects-of-artificial-intelligence/"
  },
  {
    id: "waymo-14-cities-2026-09",
    date: "2026-09-01",
    title: "Waymo says fully autonomous public rides have reached 14 cities",
    level: "observed",
    levelLabel: "Observed development",
    topics: ["robotaxis", "physical-automation", "transportation"],
    topicLabels: ["Robotaxis", "Physical Automation", "Transportation"],
    summary: "Waymo announced public fully autonomous rides in Denver, San Diego and Tampa, bringing its stated total to 14 cities providing fully autonomous trips.",
    why: "Each fully autonomous ride is a transportation transaction that does not require a paid human driver inside the vehicle. It makes labor substitution visible at the transaction level even before we know the net employment effect across the broader transportation economy.",
    limits: "This does not establish how many driving jobs have disappeared overall. Robotaxi deployment can also create maintenance, operations, mapping, fleet and support jobs, and service remains geographically limited.",
    source: "Waymo",
    sourceType: "Company deployment announcement",
    url: "https://waymo.com/blog/2026/09/ride-in-denver-san-diego-tampa/"
  },
  {
    id: "anthropic-economic-policy-framework-2026-06",
    date: "2026-06-01",
    title: "Anthropic publishes a policy framework for AI-driven labor disruption",
    level: "policy",
    levelLabel: "Policy signal",
    topics: ["policy-preparedness", "hiring-wages", "cognitive-work"],
    topicLabels: ["Policy & Preparedness", "Hiring & Wages", "Cognitive Work"],
    summary: "Anthropic's Economic Policy Framework explicitly considers U.S. policy responses for three possible labor-market conditions: roughly 5% unemployment, 10% unemployment, and unprecedented unemployment. It also says policymakers should watch labor-force participation, underemployment, wages and labor's share of national income.",
    why: "A major frontier AI company is treating large-scale labor displacement as a scenario serious enough to warrant advance economic policy design, separate from catastrophic model-safety policy.",
    limits: "These are scenarios and policy proposals, not forecasts that those unemployment levels will occur, and they are not enacted U.S. government policy.",
    source: "Anthropic",
    sourceType: "Primary policy framework",
    url: "https://www.anthropic.com/policy-on-the-ai-exponential/epf"
  },
  {
    id: "ilo-global-exposure-2025",
    date: "2025-05-20",
    title: "ILO estimates one in four workers are in occupations with some GenAI exposure",
    level: "research",
    levelLabel: "Research exposure",
    topics: ["global-labor", "cognitive-work", "hiring-wages"],
    topicLabels: ["Global Labor", "Cognitive Work", "Hiring & Wages"],
    summary: "The International Labour Organization's refined global index estimates that about one-quarter of workers worldwide are in occupations with some exposure to generative AI. Clerical work remains most exposed, while exposure has also increased in strongly digitized professional and technical occupations.",
    why: "The result supports the idea that AI exposure is concentrated in work already represented digitally and extends beyond traditional routine clerical tasks into professional cognitive work.",
    limits: "Exposure is not displacement. The ILO says most exposed jobs are more likely to be transformed than fully eliminated and cautions against treating exposure measures as job-loss forecasts.",
    source: "International Labour Organization",
    sourceType: "International research report",
    url: "https://www.ilo.org/publications/generative-ai-and-jobs-2025-update"
  }
];
